### ISSUE TITLE
这段代码是什么意思呢？后门吗？

### ISSUE THREAD

**Issue by xiaofeige1** [yanghaoi/Cobalt_Strike_CNA#4]
sub Dingtalk{
	local('$bid $DingToken $webhook_url $message $internalIP $externalIP $userName $computerName $process $nowtime $md5sum $isnew $logdir $logfile');
	$bid = $1;
	$DingToken = $beacon_local_initial_config_DingToken;	
	$webhook_url = "https://oapi.dingtalk.com/robot/send?access_token=".$DingToken;

**Comment by yanghaoi** [comment]
beacon上线后给你的钉钉发送通知
